### ISSUE TITLE
Read-only Columns

### ISSUE THREAD

**Issue by JM0804** [thomaxxl/safrs#113]
I was wondering if it's possible to create columns which are read-only when exposed via the API.

For example, I have a data model with a `last_completed` column which I want to restrict to being set or updated only via a call to a custom RPC call named `complete`, exposed with `@jsonapi_rpc`. It also has some computed values such as `due_date` which are exposed with `@jsonapi_attr`:

```python
import datetime
from dateutil.relativedelta import relativedelta
from safrs import SAFRSBase, jsonapi_attr, jsonapi_rpc
from typing import Optional

from app import db


class Task(SAFRSBase, db.Model):
    __tablename__ = 'tasks'
    id = db.Column(db.Integer, primary_key=True)
    last_completed = db.Column(db.Date, nullable=True)
    name = db.Column(db.String)

    @jsonapi_rpc(http_methods=["POST"])
    def complete(self):
        self.last_completed = datetime.datetime.now().date()

    @jsonapi_attr
    def due_date(self) -> Optional[datetime.datetime]:
        if self.last_completed:
            return self.last_completed + relativedelta(
                **{self.frequency_unit.value: self.frequency_value}
            )
        else:
            return None
```

To clarify, I would like `last_completed` and `due_date` to be available via `GET` but not `PATCH` or `POST`.

Attempting to set such a restriction with `last_completed.http_methods = ['GET']` [as suggested for relationships here](https://github.com/thomaxxl/safrs/wiki/Access-Control) doesn't work.

Perhaps there is something similar to [the hidden columns feature](https://github.com/thomaxxl/safrs/wiki/Custom-Documentation#hide-columns) that I am not seeing?

Many thanks :)

**Comment by thomaxxl** [comment]
Hi,

`due_date` in your example should not be available via `PATCH` or `POST`.  It does show up in the swagger but it should be omitted from serialization when these requests are processe.
The OAS/swagger should take this into account (i.e. not show the attribute unless a `setter` is defined), so I'll fix that.
Anyway, it is possible to update/override the swagger manually using the `custom_swagger` argument to `SAFRSAPI`, [example](https://github.com/thomaxxl/safrs/blob/master/examples/mini_examples/ex12_swagger.py). So you can use this approach to remove the attributes from the OAS spec.

Indeed, you can also use hidden columns in combination with `jsonapi_attr` to create read-only attributes because hidden columns are also not (de)serialized. Note, column names prefixed with an underscore are automatically hidden.
