### ISSUE TITLE
Why not use Flask-Restless ?

### ISSUE THREAD

**Issue by jmaynier** [thomaxxl/safrs#16]
As stated in their definition "Flask-Restless provides simple generation of ReSTful APIs for database models defined using SQLAlchemy (or Flask-SQLAlchemy)."

So it seems the obvious choice to start building on top of it to add swagger/jsonapi support. 
Did you consider it ? If so what advantages did you see in Flask-Restful ?

I have no experience in neither of Flask-Restful or Flask-Restless, so it is not a judgement, I just want to know the motivations behind your choice.

**Comment by thomaxxl** [comment]
When I started this project (~2years ago), it started out as documentation for some existing services and I used [flask-restful-swagger-2](https://github.com/soerface/flask-restful-swagger-2.0) .
From there on, I just improved the safrs code, added features and started using json:api, so it grew "organically". 
I didn't really look into other libraries either and I have no idea if using flask-restless would be an improvement at this point. 
Currently, the safrs source code is ~3K LoC which is fairly small. Since I wrote all of it myself, I can quickly debug any issues (also, I'd rather debug my own code :) ) . I am not aware of any major bugs, however there are still a lot of things that can be improved.
If someone would pay me to use flask-restless, I would happily integrate it though :), but then again, I have no idea why this would be better: 
- The interface I created for the users/developers doesn't care about the underlying implementation
- I don't know if there would be performance improvements (I don't think so, but then again I don't really know flask-restless) 

Also, most of the work I put into this project is finetuning small details. I have no idea how flask-restless handles the issues I had to resolve to get where we are atm. 

Please let me know if something isn't clear and I'll try to explain.

**Comment by jrc** [comment]
As of this writing, Flask-Restless was last updated Mar 2017. I wouldn't be comfortable depending on something that's not being actively maintained. 

Meanwhile, Flask-RESTful depends on legacy parsing/serialization code instead of Marshmallow. From some of the most recent comments on https://github.com/flask-restful/flask-restful/issues/335:

- "If you're a newcomer and you start building your project with flask-restful, you soon realize that there're lots of limitations of regparse and marshal."
- "I would say that a lot of what Flask-RESTful does is better handled by composing more atomic libraries – essentially just using Marshmallow plus Flask MethodViews gets you a lot of the way. Content negotiation is something unique to Flask-RESTful, though – but many APIs don't need that."

**Comment by thomaxxl** [comment]
Safrs no longer relies on marshmallow either (serialization is actually pretty simple in our case. jsonapi structuring is more complex). 
I have no strong feelings about other packages, but I do like to  be able to rely on a number of narrow-focus packages with well-defined functionality. This makes architecture and debugging easier.

I'll close this, feel free to (re)open if there are other questions or suggestions.
