### ISSUE TITLE
Subclassing db.Model

### ISSUE THREAD

**Issue by michaelkrupp** [thomaxxl/safrs#21]
from [Limitations & TODOs](https://github.com/thomaxxl/safrs#limitations--todos):
> I am not a big fan of the multiple inheritance needed to declare SAFRSBase instances but I couldn't subclass sqla's db.Model and I think inheritance is more clear than class decorators.

This is actually pretty easy.
All you need to do is pass your custom class to the constructor of SQLAlchemy:

```python
from flask_sqlalchemy import SQLAlchemy
from flask_sqlalchemy.model import Model
from sqlalchemy.ext.declarative import declarative_base
from safrs import SAFRSBase

MODEL_NAME='Model'

class SAFRSModel(SAFRSBase, Model):
  pass

db = SQLAlchemy(model_class=declarative_base(cls=SAFRSModel, name=MODEL_NAME))

class Users(db.Model):
  __tablename__ = 'users'
```

You could even go so far and automatically expose SAFRSBase models via a custom Metaclass:

```python
from flask_sqlalchemy import SQLAlchemy
from flask_sqlalchemy.model import Model, DefaultMeta
from sqlalchemy.ext.declarative import declarative_base
from safrs import SAFRSBase, Api

MODEL_NAME='Model'

api = Api(...)

class SAFRSModel(SAFRSBase, Model):
  pass

class SAFRSMeta(DefaultMeta):
  def __init__(cls, name, bases, d):
    if name != MODEL_NAME and issubclass(cls, SAFRSModel):
      api.expose_object(cls)
    super(_DbMeta, cls).__init__(name, bases, d)

db = SQLAlchemy(model_class=declarative_base(cls=SAFRSModel, name=MODEL_NAME))

class Users(db.Model):
  __tablename__ = 'users'
```

In case you are interested, let me know and I'll put up a PR when I find some free time :-)

**Comment by thomaxxl** [comment]
Wow, that would be great :) if you could manage to make it backwards compatible I'll test & merge it asap.

I came across the model_class a couple of times since I put that comment in the readme but I never tried to implement it because of a) time, b) fear (things might break and everything seems to work now as is)

If you have more ideas, please feel free to open a ticket and I'll look into it eventually.

**Comment by thomaxxl** [comment]
For the record, implementing this is very hard, especially if you're not familiar with the safrs internals, because SAFRSBase uses the sqla mapper from the db.Model and the model_class isn't really suppsed to access the orm. I need to redesign the SAFRSBase structure to properly implement it. 
I hope to find the time to do it but it'll take me a couple of days unfortunately :/.
I'll leave this issue open until then.

**Comment by thomaxxl** [comment]
I won't implement this for now, sqla doesn't allow for it and it's supposed to be extended like this...
https://docs.sqlalchemy.org/en/latest/orm/extensions/declarative/mixins.html
