### ISSUE TITLE
about safrs/db.py when column  type is datetime/date , format Error.

### ISSUE THREAD

**Issue by janl99** [thomaxxl/safrs#25]
I use datetime format is '%Y-%m-%d %H:%M:%S'  and when value is None , it can't work.
```
 # Parse datetime and date values
    try:
        if column.type.python_type == datetime.datetime:
            arg_value = datetime.datetime.strptime(str(arg_value), '%Y-%m-%d %H:%M:%S.%f')
        elif column.type.python_type == datetime.date:
            arg_value = datetime.datetime.strptime(str(arg_value), '%Y-%m-%d')
    except (NotImplementedError, ValueError) as exc:
        safrs.log.warning('datetime {} for value "{}"'.format(exc, arg_value))

    return arg_value
```

And i want to change the code like this:

```
 # Parse datetime and date values
     if arg_value is not None:
         try:
            if column.type.python_type == datetime.datetime:
                arg_value = datetime.datetime.strptime(str(arg_value), '%Y-%m-%d %H:%M:%S')
            elif column.type.python_type == datetime.date:
                arg_value = datetime.datetime.strptime(str(arg_value), '%Y-%m-%d')
        except (NotImplementedError, ValueError) as exc:
            safrs.log.warning('datetime {} for value "{}"'.format(exc, arg_value))

    return arg_value
```

**Comment by thomaxxl** [comment]
Hi, thanks for informing me about this problem.
The date parsing is a bit of a problem indeed.
I'll try to incorporate your change asap.

You can also override __init__ and parse the json values before calling SAFSBase.__init__ .
The constructor isn't called when updating/patching the values however, so I'll have to find a better solution for parsing date values.
Yet another solution may be to create a custom sqlalchemy column type.

This is the only default datatype i've had issues with because the casting needs to be customized.

Anyway, I'll update this issue when I've found the time to implement a solution.

**Comment by janl99** [comment]
thanks .

**Comment by thomaxxl** [comment]
v2.0.0 has been uploaded to pypi which includes this. Can you verify this works for you? Thanks.
