### ISSUE TITLE
Disable Swagger UI in production

### ISSUE THREAD

**Issue by ISBrunoPires** [thomaxxl/safrs#73]
Hi,

great project! The integrated Swagger UI facilitates service integrations for our frontend team. However i've been asking myself if there's any way to easily disable Swagger UI in production mode?

Best Regards,
Bruno

**Comment by thomaxxl** [comment]
The swagger blueprint is created in https://github.com/thomaxxl/safrs/blob/master/safrs/safrs_init.py#L69

It used to be possible to customize or disable it by passing a custom blueprint. This no longer works since I refactored it and didn't test this.. I'll reactivate it.
In the mean time, maybe you can override the `SAFRS.init_app`.

Another solution may be to check the `request.url` in an `@app.before_request` function (this is how I would've solved it if I wasn't familiar with the code :) )
