### ISSUE TITLE
extend API with custom classes

### ISSUE THREAD

**Issue by rule88** [thomaxxl/safrs#80]
Hi,

how can I add custom routes to the API?

Currently I do have for all tables CRUD operations, but I would like to proceed by creating "psuedo" models that will output custom json.

**Comment by thomaxxl** [comment]
Here's an example how you can expose custom classes: https://github.com/thomaxxl/safrs/blob/master/examples/demo_stateless.py

Defining custom classes quite complex because of the jsonapi serialization requirements.
It's also possible to add other flask routes, then you have to modify the swagger manually (which can be added using the "custom_swagger" argument to `SAFRSAPI`).

Lmk when you need more clarification.
