### ISSUE TITLE
Swagger generation removing plurals

### ISSUE THREAD

**Issue by nickmcsimpson** [thomaxxl/safrs#89]
I'm testing out the JSONAPI integration and when generating the swagger UI, the routes are being constructed incorrectly causing it to not actually work. The expected and working route is `/persons` but the Swagger page shows `/person` and won't work.

I've tried modifying names throughout the small test app to see where this is being generated from, but I think the script is intentionally lopping off the 's' when making these routes. Both flask-rest-jsonapi and SAFRS are new to me, so I may have configured something incorrectly.

This _should_ be explicitly incorrect based on the routes that are configured for the API. I've created this app almost entirely from documentation:
[Flask Rest JSONAPI](https://flask-rest-jsonapi.readthedocs.io/)
This app works & [Swagger Blog for this](https://swagger.io/blog/api-development/automatically-generating-swagger-specifications-wi/)

*Route Declarations*:
```
def create_app(config_filename=None, host="localhost"):
        app = Flask(__name__)
        app.config.update(SQLALCHEMY_DATABASE_URI="postgresql://")
        app.config['SQLALCHEMY_DATABASE_URI'] = 'A_URL_HERE'
        db.app = app
        db.init_app(app)
        api = Api(app)
        # Notice the route is /persons
        api.route(PersonList, "person_list", "/persons")
        api.route(
            PersonDetail, "person_detail", "/persons/<int:id>", "/computers/<int:computer_id>/owner"
        )
        # api.route(PersonRelationship, 'person_computers', '/persons/<int:id>/relationships/computers')
        api.route(
            PersonRelationship,
            "person_computers",
            "/persons/<int:id>/relationships/computers",
        )
        ... more routes
```

But this is not what's being created on the Swagger page:
![Screen Shot 2021-01-26 at 9 50 36 AM](https://user-images.githubusercontent.com/25393558/105868601-f3e00500-5fbb-11eb-96a5-f09b091f7cdf.png)

This means that the Swagger page doesn't actually work. The routes work fine if hit correctly through another method.

What am I doing wrong here?

**Comment by thomaxxl** [comment]
Hi,

I guess you're talking about [demo_flaskrestjsonapi.py](https://github.com/thomaxxl/safrs/blob/master/examples/demo_flaskrestjsonapi.py) ? I didn't add this example, I just accepted a PR from @kurianbenoy-aot . SAFRS has its own jsonapi serialization implementation which does not rely on flask-rest-jsonapi.

By default, safrs generates collection routes based in the `__tablename__` variable. So maybe you can add

```python
class Person(db.Model, SAFRSBase):
    __tablename__ = "persons"
```
another solution might be to override `SAFRSBase._s_collection_name` for your model:

```python
Person._s_collection_name = "persons"
```
(Collection names are generated based on this property)
https://github.com/thomaxxl/safrs/blob/b09bd8546a7e606b6da22f5d4e3e4b4b74994c37/safrs/base.py#L658 


Anyway, I can't provide much support for flask-rest-jsonapi integration because I don't use it myself.
